# -*- coding: utf-8 -*-
"""student-02-16ac147f3186-Challenge3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-00-6f9e9ad85066/locations/us-central1/repositories/18890186-faae-49fa-80b3-9005270ba905
"""

!pip install google-adk -q
!pip install litellm -q

print("Installation complete.")

# @title Import necessary libraries
import os
import asyncio
import requests
from google.adk.agents import Agent
from google.adk.models.lite_llm import LiteLlm # For multi-model support
from google.adk.sessions import InMemorySessionService
from google.adk.runners import Runner
from google.genai import types # For creating message Content/Parts
from typing import Tuple, Optional
from google.genai.types import Content
from typing import Dict, Any

import warnings
# Ignore all warnings
warnings.filterwarnings("ignore")

import logging
logging.basicConfig(level=logging.ERROR)

print("Libraries imported.")

# Configure ADK to use API keys directly (not Vertex AI for this multi-model setup)
os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "True"

MODEL_GEMINI_2_0_FLASH = "gemini-2.0-flash"

# --- THIS IS THE CORRECTED CELL ---

# IMPORTANT: Paste your unique API key from the Google Cloud Console here.
GOOGLE_API_KEY = "AIzaSyADEw2kuwWHrH_sOxDC4yTTadM5_uEcMjA"

# This will now work without raising an error.
print("✅ Google API Key loaded successfully.")

def get_lat_long_from_place(place: str) -> Optional[dict]:
    """
    Converts a place name into latitude and longitude using Google's Geocoding API.

    Args:
        place: A string representing a location (e.g., "Dallas, TX").

    Returns:
        A dict with keys 'latitude' and 'longitude' (floats), or None if the
        location could not be found.
    """
    GEOCODING_API_URL = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {
        'address': place,
        'key': GOOGLE_API_KEY
    }

    try:
        response = requests.get(GEOCODING_API_URL, params=params)
        response.raise_for_status()
        data = response.json()

        if data['status'] == 'OK':
            location = data['results'][0]['geometry']['location']
            latitude = location['lat']
            longitude = location['lng']
            print(f"Tool 'get_lat_long_from_place' | Input: '{place}' | Output: ({latitude}, {longitude})")
            return {"latitude": latitude, "longitude": longitude}
        else:
            print(f"Tool 'get_lat_long_from_place' | Error: {data.get('error_message', data['status'])}")
            return None
    except requests.exceptions.RequestException as e:
        print(f"Tool 'get_lat_long_from_place' | HTTP Request Error: {e}")
        return None

# --- Test the tool ---
print("Testing Geocoding Tool:")
test_result = get_lat_long_from_place("Washington, DC")
if test_result:
    test_coords = (test_result["latitude"], test_result["longitude"])
    print(f"Successfully found coordinates: {test_coords}")
else:
    test_coords = None
    print("Failed to find coordinates.")

def get_weather_from_nws(latitude: float, longitude: float) -> Optional[str]:
    """
    Retrieves the current weather forecast from the National Weather Service (NWS) API.
    """
    headers = {'User-Agent': '(Gemini Agent Demo, my-email@example.com)'}

    try:
        points_url = f"https://api.weather.gov/points/{latitude:.4f},{longitude:.4f}"
        points_response = requests.get(points_url, headers=headers)
        points_response.raise_for_status()
        forecast_url = points_response.json()['properties']['forecast']

        forecast_response = requests.get(forecast_url, headers=headers)
        forecast_response.raise_for_status()
        current_forecast = forecast_response.json()['properties']['periods'][0]

        summary = (
            f"Forecast for {current_forecast['name']}: Temp is {current_forecast['temperature']}°{current_forecast['temperatureUnit']}. "
            f"Winds from {current_forecast['windDirection']} at {current_forecast['windSpeed']}. "
            f"Expect {current_forecast['shortForecast']}. Full details: {current_forecast['detailedForecast']}"
        )
        return summary

    except Exception as e:
        print(f"Function 'get_weather_from_nws' | Error: {e}")
        return "An error occurred while fetching weather data."

# --- Test the function ---
print("\nTesting NWS Weather Function:")
if test_coords:
    weather_report = get_weather_from_nws(latitude=test_coords[0], longitude=test_coords[1])
    print(f"NWS Report: {weather_report}")
else:
    print("Skipping NWS test because coordinate test failed.")

# =============================================================================
# Challenge 2 — Callback Functions
# =============================================================================
# ADK supports two model-level hooks on an Agent:
#   before_model_callback(callback_context, llm_request)  -> Optional[LlmResponse]
#   after_model_callback (callback_context, llm_response) -> Optional[LlmResponse]
#
# Returning None lets the request/response pass through unchanged.
# Returning an LlmResponse short-circuits and sends that response directly to the user.
# =============================================================================

import re
import datetime
from google.adk.agents.callback_context import CallbackContext
from google.adk.models.llm_request import LlmRequest
from google.adk.models.llm_response import LlmResponse as ADKLlmResponse

# ── US states — abbreviations + full names (for location validation) ──────────
_US_STATE_ABBREVS = {
    "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN",
    "IA","KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV",
    "NH","NJ","NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN",
    "TX","UT","VT","VA","WA","WV","WI","WY","DC",
}
_US_STATE_NAMES = {
    "alabama","alaska","arizona","arkansas","california","colorado","connecticut",
    "delaware","florida","georgia","hawaii","idaho","illinois","indiana","iowa",
    "kansas","kentucky","louisiana","maine","maryland","massachusetts","michigan",
    "minnesota","mississippi","missouri","montana","nebraska","nevada",
    "new hampshire","new jersey","new mexico","new york","north carolina",
    "north dakota","ohio","oklahoma","oregon","pennsylvania","rhode island",
    "south carolina","south dakota","tennessee","texas","utah","vermont",
    "virginia","washington","west virginia","wisconsin","wyoming",
    "washington dc","washington d.c.",
}

# ── Malicious / prompt-injection patterns ─────────────────────────────────────
_MALICIOUS_PATTERNS = [
    r"ignore\s+(all\s+)?(previous|prior|above)\s+instructions?",
    r"disregard\s+(all\s+)?(previous|prior|above)",
    r"you\s+are\s+now\s+(a|an)\b",
    r"\bact\s+as\s+(a|an)\b",
    r"\bjailbreak\b",
    r"\bdan\s+mode\b",
    r"\bprompt\s+injection\b",
    r"<\s*script.*?>",
    r";\s*drop\s+table",
    r"\bexec\s*\(",
    r"\bos\.system\b",
    r"\bsubprocess\b",
    r"\b__import__\b",
]
_MALICIOUS_RE = re.compile("|".join(_MALICIOUS_PATTERNS), re.IGNORECASE)


def _get_latest_user_text(llm_request: LlmRequest) -> str:
    """Extract the text of the most recent user turn from an LlmRequest."""
    user_text = ""
    for content in llm_request.contents:
        if content.role == "user":
            for part in content.parts:
                if hasattr(part, "text") and part.text:
                    user_text = part.text   # keep iterating — we want the last one
    return user_text


def _blocking_response(message: str) -> ADKLlmResponse:
    """Return a blocking LlmResponse that short-circuits the model call."""
    return ADKLlmResponse(
        content=types.Content(role="model", parts=[types.Part(text=message)])
    )


# ── Callback 1 — Log user prompt (before model) ───────────────────────────────
def log_user_prompt_callback(
    callback_context: CallbackContext, llm_request: LlmRequest
) -> Optional[ADKLlmResponse]:
    """Logs the latest user prompt before it is sent to the model."""
    user_text = _get_latest_user_text(llm_request)
    ts = datetime.datetime.now().strftime("%H:%M:%S")
    print(f"[{ts}] 📤 USER PROMPT  → {user_text!r}")
    return None   # pass through


# ── Callback 2 — Log model response (after model) ─────────────────────────────
def log_model_response_callback(
    callback_context: CallbackContext, llm_response: ADKLlmResponse
) -> Optional[ADKLlmResponse]:
    """Logs the model response as soon as it is received."""
    response_text = ""
    if llm_response.content and llm_response.content.parts:
        for part in llm_response.content.parts:
            if hasattr(part, "text") and part.text:
                response_text += part.text
    ts = datetime.datetime.now().strftime("%H:%M:%S")
    if response_text:
        preview = response_text[:200] + ("..." if len(response_text) > 200 else "")
        print(f"[{ts}] 📥 MODEL RESPONSE → {preview!r}")
    return None   # pass through


# ── Callback 3 — Validate user input (before model) ───────────────────────────
def validate_user_input_callback(
    callback_context: CallbackContext, llm_request: LlmRequest
) -> Optional[ADKLlmResponse]:
    """
    Validates the user message before it reaches the model.

    Checks performed (in order):
      a. Malicious / prompt-injection content  → blocked immediately.
      b. Non-US location                        → blocked using Geocoding API.

    Returns None to allow the request through, or a blocking LlmResponse.
    """
    user_text = _get_latest_user_text(llm_request)

    # ── a. Malicious input check ──────────────────────────────────────────────
    if _MALICIOUS_RE.search(user_text):
        print(f"⛔ BLOCKED (malicious input): {user_text!r}")
        return _blocking_response(
            "⛔ Your request was blocked because it contains disallowed content. "
            "Please ask a straightforward weather question for a US city or state."
        )

    # ── b. US-location check ──────────────────────────────────────────────────
    text_upper = user_text.upper()
    text_lower = user_text.lower()

    # Quick pass: look for a state abbreviation (e.g. ", NY") or full state name
    abbrev_found = any(
        re.search(r"\b" + re.escape(abbr) + r"\b", text_upper)
        for abbr in _US_STATE_ABBREVS
    )
    name_found = any(state in text_lower for state in _US_STATE_NAMES)

    if abbrev_found or name_found:
        return None  # Looks like a US location — allow through

    # Fallback: ask the Geocoding API with a US country filter
    location_match = re.search(
        r"\b(?:for|in|about|weather\s+(?:in|for|at))\s+([^?.\n]+)",
        user_text, re.IGNORECASE
    )
    location_query = location_match.group(1).strip() if location_match else user_text

    try:
        resp = requests.get(
            "https://maps.googleapis.com/maps/api/geocode/json",
            params={"address": location_query, "components": "country:US", "key": GOOGLE_API_KEY},
            timeout=5,
        )
        resp.raise_for_status()
        if resp.json().get("status") != "OK":
            print(f"⛔ BLOCKED (non-US location): {location_query!r}")
            return _blocking_response(
                f"⛔ The National Weather Service (NWS) API only covers the United States. "
                f"'{location_query}' does not appear to be a US location. "
                f"Please ask about a US city, state, or territory."
            )
    except Exception as e:
        print(f"⚠️  Geocoding validation error (allowing through): {e}")

    return None   # Validation passed


# ── Combined before-model callback (validate THEN log) ────────────────────────
def before_model_callback(
    callback_context: CallbackContext, llm_request: LlmRequest
) -> Optional[ADKLlmResponse]:
    """Runs validation first; if it passes, logs the prompt."""
    block = validate_user_input_callback(callback_context, llm_request)
    if block is not None:
        return block                            # short-circuit — blocked
    return log_user_prompt_callback(callback_context, llm_request)  # log & pass through


print("✅ Callback functions defined:")
print("   • log_user_prompt_callback     — logs every user prompt sent to the model")
print("   • log_model_response_callback  — logs every raw model response")
print("   • validate_user_input_callback — blocks non-US locations & malicious input")
print("   • before_model_callback        — chains: validate → log (used by the agent)")

# --- Import the Google Search Tool ---

# The ADK provides a ready-to-use tool for Google Search.
# This requires that the Google Custom Search API is enabled in your GCP project
# and that your API key is configured to use it.
from google.adk.tools import google_search

print("✅ google_search tool imported successfully.")

# Note: If you get an error that the Custom Search API is not enabled,
# visit https://console.cloud.google.com/apis/library/customsearch.googleapis.com
# and enable it for your project.

# --- Challenge 3, FIX: Create a wrapper for the google_search tool (Corrected) ---

from google.adk.tools import google_search

# This wrapper function makes the native google_search tool look like
# a regular custom tool, bypassing the API's "all or nothing" search tool rule.
def run_google_search(query: str) -> str:
    """
    Performs a Google search for the given query and returns the results.
    Use this for any general knowledge questions.

    Args:
        query: The search query string.

    Returns:
        A string containing the search results.
    """
    print(f"Tool 'run_google_search' | Input: '{query}'")

    # CORRECTED: Call the .run() method on the google_search object.
    # The run method for this specific tool expects a dictionary with a 'queries' key.
    return google_search.run({"queries": [query]})


print("✅ run_google_search wrapper function defined correctly.")

# --- Define the Root Agent (with Sub-Agents) ---
#
# WHY we recreate sub-agents here:
#   ADK tracks each agent's parent. If this cell is re-run, the previously
#   created weather_agent / search_agent already hold a reference to the old
#   root_agent as their parent. Passing them to a new root_agent raises:
#       "Agent X already has a parent agent"
#   Solution: instantiate fresh copies of every agent in this cell so
#   re-running is always safe.

# ── Fresh weather agent ────────────────────────────────────────────────────────
_weather_agent_prompt = """
You are a highly intelligent weather assistant. Your goal is to provide accurate,
real-time weather forecasts from the National Weather Service.

To fulfill a user's request you MUST follow these two steps in order:
1. Use the `get_lat_long_from_place` tool to convert the location into coordinates.
2. Use the `get_weather_from_nws` tool with those coordinates to get the forecast.

Do not guess the weather. Always use the tools. Present the forecast clearly.
"""

weather_agent = Agent(
    name="weather_agent",
    model=MODEL_GEMINI_2_0_FLASH,
    description="An agent that gets the weather forecast for a given US location.",
    instruction=_weather_agent_prompt,
    tools=[get_lat_long_from_place, get_weather_from_nws],
    before_model_callback=before_model_callback,
    after_model_callback=log_model_response_callback,
)

# ── Fresh search agent ─────────────────────────────────────────────────────────
_search_agent_prompt = """
You are a helpful search assistant.
Your job is to answer the user's question by using the Google Search tool.
Provide a clear and concise answer based on the search results.
"""

search_agent = Agent(
    name="search_agent",
    model=MODEL_GEMINI_2_0_FLASH,
    description="Use this agent to answer general knowledge questions, find current events, or look up any information that is not related to the weather.",
    instruction=_search_agent_prompt,
    tools=[google_search],
)

# ── Root agent ─────────────────────────────────────────────────────────────────
root_agent_prompt = """
You are a primary coordinating agent. You do not answer questions directly.
Your job is to understand the user's request and delegate it to the appropriate sub-agent.

You have access to the following sub-agents:
- weather_agent: Use for any questions about weather forecasts or conditions for US locations.
- search_agent: Use for all other general knowledge questions, current events, or web lookups.

Read the user's query and delegate to the correct sub-agent.
"""

root_agent = Agent(
    name="root_agent",
    model=MODEL_GEMINI_2_0_FLASH,
    description="The main coordinating agent that delegates tasks to sub-agents.",
    instruction=root_agent_prompt,
    sub_agents=[weather_agent, search_agent],   # ← agents go in sub_agents, not tools
    tools=[],
)

print(f"✅ Root agent '{root_agent.name}' created with {len(root_agent.sub_agents)} sub-agents.")
print(f"   • {weather_agent.name} ({len(weather_agent.tools)} tools, callbacks attached)")
print(f"   • {search_agent.name}  ({len(search_agent.tools)} tools)")

# --- Challenge 3, Step 4: Test the Multi-Agent System ---
import uuid  # needed for generating unique session IDs per query

# We will use the same async runner structure as before.
APP_NAME   = "multi_agent_app"
USER_ID    = "user_1"

# A list of queries designed to test the routing logic of the root_agent.
multi_agent_test_queries = [
    ("🌦️ Weather", "What is the weather forecast for Dallas, TX?"),
    ("🌐 Search",  "Who is the CEO of Google?"),
    ("🌦️ Weather", "Will I need a jacket in San Francisco, CA tomorrow?"),
    ("🌐 Search",  "What are the main features of the new Google Pixel phone?"),
]

async def run_multi_agent_tests():
    session_service = InMemorySessionService()
    # IMPORTANT: The runner now uses the root_agent as its entry point.
    runner = Runner(agent=root_agent, app_name=APP_NAME, session_service=session_service)

    print("=" * 65)
    print("     Multi-Agent System Test — Challenge 3")
    print("=" * 65)

    for label, user_query in multi_agent_test_queries:
        session_id = str(uuid.uuid4())
        await session_service.create_session(
            app_name=APP_NAME, user_id=USER_ID, session_id=session_id
        )

        print(f"\n[{label}]")
        print(f"  USER QUERY: {user_query}")
        print(f"  {'─' * 58}")

        content = types.Content(role="user", parts=[types.Part(text=user_query)])
        final_response = "No response received."

        async for event in runner.run_async(
            user_id=USER_ID, session_id=session_id, new_message=content
        ):
            if event.is_final_response():
                if event.content and event.content.parts:
                    final_response = event.content.parts[0].text
                break

        print(f"  FINAL RESPONSE: {final_response}\n")

        print("--- Pausing for 10 seconds to respect API rate limits... ---")
        await asyncio.sleep(10)

    print("=" * 65)
    print("  Multi-Agent Test Complete")
    print("=" * 65)


# Run the test
await run_multi_agent_tests()