# -*- coding: utf-8 -*-
"""student-02-16ac147f3186-Challenge4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-00-6f9e9ad85066/locations/us-central1/repositories/64743de3-4030-4775-ba61-a5b7fef312f7
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install google-adk -q
# %pip install litellm -q
# %pip install wikipedia -q
# %pip install langchain-community -q

print("Installation complete.")

# @title Import necessary libraries
import os
import asyncio
import uuid
import requests
from typing import Optional

# ADK core
from google.adk.agents import Agent, SequentialAgent, LoopAgent, ParallelAgent
from google.adk.sessions import InMemorySessionService
from google.adk.runners import Runner
from google.adk.tools.tool_context import ToolContext
from google.adk.tools.langchain_tool import LangchainTool
from google.adk.tools import exit_loop

from google.adk.agents.callback_context import CallbackContext
from google.adk.models import LlmResponse, LlmRequest

# Google GenAI types
from google.genai import types

# LangChain / Wikipedia
from langchain_community.tools import WikipediaQueryRun
from langchain_community.utilities import WikipediaAPIWrapper

import warnings
warnings.filterwarnings("ignore")

import logging
logging.basicConfig(level=logging.ERROR)

print("Libraries imported.")

# Configure ADK to use API keys directly (not Vertex AI for this multi-model setup)
os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "True"

MODEL_GEMINI_2_0_FLASH = "gemini-2.0-flash"

# --- THIS IS THE CORRECTED CELL ---

# IMPORTANT: Paste your unique API key from the Google Cloud Console here.
GOOGLE_API_KEY = "AIzaSyADEw2kuwWHrH_sOxDC4yTTadM5_uEcMjA"

# This will now work without raising an error.
print("✅ Google API Key loaded successfully.")

import datetime

def log_query_to_model(callback_context: CallbackContext, llm_request: LlmRequest):
    """Logs the user prompt before it is sent to the model."""
    if llm_request.contents and llm_request.contents[-1].role == 'user':
        for part in llm_request.contents[-1].parts:
            if part.text:
                ts = datetime.datetime.now().strftime("%H:%M:%S")
                print(f"[{ts}] 📤 USER PROMPT → [{callback_context.agent_name}]: {part.text[:200]!r}")

def log_model_response(callback_context: CallbackContext, llm_response: LlmResponse):
    """Logs the model response as soon as it is received."""
    if llm_response.content and llm_response.content.parts:
        for part in llm_response.content.parts:
            ts = datetime.datetime.now().strftime("%H:%M:%S")
            if part.text:
                preview = part.text[:200] + ("..." if len(part.text) > 200 else "")
                print(f"[{ts}] 📥 MODEL RESPONSE ← [{callback_context.agent_name}]: {preview!r}")
            elif part.function_call:
                print(f"[{ts}] 🔧 FUNCTION CALL ← [{callback_context.agent_name}]: {part.function_call.name}")

#Tools

def append_to_state(
    tool_context: ToolContext, field: str, response: str
) -> dict[str, str]:
    """Append new output to an existing state key.

    Args:
        field (str): a field name to append to
        response (str): a string to append to the field

    Returns:
        dict[str, str]: {"status": "success"}
    """
    existing_state = tool_context.state.get(field, [])
    tool_context.state[field] = existing_state + [response]
    logging.info(f"[Added to {field}] {response}")
    return {"status": "success"}


def write_file(
    tool_context: ToolContext,
    directory: str,
    filename: str,
    content: str
) -> dict[str, str]:
    target_path = os.path.join(directory, filename)
    os.makedirs(os.path.dirname(target_path), exist_ok=True)
    with open(target_path, "w") as f:
        f.write(content)
    return {"status": "success"}

# --- Search Agent ---
# Finds information from Wikipedia to answer the user's question.

search_agent = Agent(
    name="search_agent",
    model=MODEL_GEMINI_2_0_FLASH,
    description="Searches Wikipedia to find data that answers the user's question.",
    instruction="""
    QUESTION:
    { user_question? }

    INSTRUCTIONS:
    - Use your Wikipedia tool to search for relevant, factual information to answer the QUESTION above.
    - Compile the research into a clear and factual initial answer.
    - Use the 'append_to_state' tool to save your answer to the field 'initial_answer'.
    - Summarize the key facts you found.
    """,
    before_model_callback=log_query_to_model,
    after_model_callback=log_model_response,
    tools=[
        LangchainTool(tool=WikipediaQueryRun(api_wrapper=WikipediaAPIWrapper())),
        append_to_state,
    ],
)

# --- Critique Agent ---
# Reviews the initial answer and suggests specific improvements.

critique_agent = Agent(
    name="critique_agent",
    model=MODEL_GEMINI_2_0_FLASH,
    description="Reviews the initial answer and makes suggestions on how it can be improved.",
    instruction="""
    QUESTION:
    { user_question? }

    INITIAL ANSWER:
    { initial_answer? }

    INSTRUCTIONS:
    - Carefully review the INITIAL ANSWER in the context of the QUESTION.
    - Evaluate it for: accuracy, completeness, clarity, and conciseness.
    - Identify any missing details, inaccuracies, or areas that are unclear.
    - List specific, actionable suggestions for improvement.
    - Use the 'append_to_state' tool to save your critique to the field 'critique_feedback'.
    - Summarize the key improvements needed.
    """,
    before_model_callback=log_query_to_model,
    after_model_callback=log_model_response,
    tools=[append_to_state],
)

# --- Refine Agent ---
# Rewrites the answer based on the critique feedback.

refine_agent = Agent(
    name="refine_agent",
    model=MODEL_GEMINI_2_0_FLASH,
    description="Rewrites the answer based on the improvements suggested by the critique agent.",
    instruction="""
    QUESTION:
    { user_question? }

    INITIAL ANSWER:
    { initial_answer? }

    CRITIQUE FEEDBACK:
    { critique_feedback? }

    INSTRUCTIONS:
    Step 1 — Rewrite the INITIAL ANSWER by incorporating ALL suggestions from the CRITIQUE FEEDBACK.
             Ensure the refined answer is accurate, clear, complete, and well-structured.

    Step 2 — You MUST call the 'append_to_state' tool to save your refined answer to the field
             'refined_answer'. Do NOT skip this step. You are not done until you have called
             'append_to_state' with field='refined_answer'.

    Step 3 — After saving, confirm the answer was stored successfully.

    Important: Do not include commentary about changes made — provide only the polished, improved answer.
    """,
    before_model_callback=log_query_to_model,
    after_model_callback=log_model_response,
    tools=[append_to_state],
)

# --- Answer Team (Sequential Pipeline) ---
# 1. search_agent  → finds data to answer the question
# 2. critique_agent → reviews the answer and suggests improvements
# 3. refine_agent  → rewrites the answer based on the feedback

answer_team = SequentialAgent(
    name="answer_team",
    description="Answers a question by searching for information, critiquing the initial answer, and refining it.",
    sub_agents=[search_agent, critique_agent, refine_agent],
)

# --- Greeter / Root Agent ---
# Welcomes the user, collects their question, and routes to the answer_team.

root_agent = Agent(
    name="greeter",
    model=MODEL_GEMINI_2_0_FLASH,
    description="Greets the user, collects their question, and passes it to the answer team.",
    instruction="""
    Warmly greet the user and let them know you can answer their questions thoroughly
    by researching, reviewing, and refining the response before returning it.

    When the user provides a question:
    - Use the 'append_to_state' tool to save their question to the field 'user_question'.
    - Then transfer to the 'answer_team' agent to process and answer it.
    """,
    before_model_callback=log_query_to_model,
    after_model_callback=log_model_response,
    tools=[append_to_state],
    sub_agents=[answer_team],
)

# --- Test the Multi-Agent Q&A Pipeline ---
# Streams all agent events and then prints each pipeline stage from session state.

APP_NAME = "qa_pipeline_app"
USER_ID  = "user_1"

async def run_qa_pipeline(user_question: str) -> None:
    session_id = str(uuid.uuid4())

    session_service = InMemorySessionService()
    await session_service.create_session(
        app_name=APP_NAME, user_id=USER_ID, session_id=session_id
    )

    runner = Runner(agent=root_agent, app_name=APP_NAME, session_service=session_service)

    print("=" * 70)
    print("  Challenge 4 — Q&A Pipeline: Search → Critique → Refine")
    print("=" * 70)
    print(f"\n  USER QUESTION: {user_question}\n")

    content = types.Content(role="user", parts=[types.Part(text=user_question)])

    # --- Stream all events to show sub-agent activity ---
    print("─" * 70)
    print("  📡 LIVE EVENT STREAM")
    print("─" * 70)

    async for event in runner.run_async(
        user_id=USER_ID, session_id=session_id, new_message=content
    ):
        author = getattr(event, "author", None)
        if author and event.content and event.content.parts:
            for part in event.content.parts:
                if part.text and part.text.strip():
                    preview = part.text.strip()[:200] + ("..." if len(part.text.strip()) > 200 else "")
                    print(f"\n  [{author}]\n  {preview}")
                elif part.function_call:
                    print(f"\n  [{author}] 🔧 → {part.function_call.name}({list(part.function_call.args.keys())})")

    # --- Inspect session state to verify each stage ran ---
    session = await session_service.get_session(
        app_name=APP_NAME, user_id=USER_ID, session_id=session_id
    )
    state = session.state

    def get_state_text(key):
        val = state.get(key, None)
        if not val:
            return "  ⚠️  Not found in state — this stage may not have run."
        if isinstance(val, list):
            return "\n".join(str(v) for v in val)
        return str(val)

    print("\n\n" + "=" * 70)
    print("  🔍 STAGE 1 — SEARCH AGENT: Initial Answer")
    print("=" * 70)
    print(get_state_text("initial_answer"))

    print("\n\n" + "=" * 70)
    print("  ✍️  STAGE 2 — CRITIQUE AGENT: Feedback")
    print("=" * 70)
    print(get_state_text("critique_feedback"))

    print("\n\n" + "=" * 70)
    print("  ✅ STAGE 3 — REFINE AGENT: Refined Answer")
    print("=" * 70)
    print(get_state_text("refined_answer"))

    print("\n" + "=" * 70)
    print("  Pipeline Complete")
    print("=" * 70)


await run_qa_pipeline("What were Marie Curie's most significant scientific contributions?")