# -*- coding: utf-8 -*-
"""student-02-16ac147f3186-Challenge1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-00-6f9e9ad85066/locations/us-central1/repositories/fcd02007-d82d-4c02-a22e-49c82ef15497
"""

!pip install google-adk -q
!pip install litellm -q

print("Installation complete.")

# @title Import necessary libraries
import os
import asyncio
import requests
from google.adk.agents import Agent
from google.adk.models.lite_llm import LiteLlm # For multi-model support
from google.adk.sessions import InMemorySessionService
from google.adk.runners import Runner
from google.genai import types # For creating message Content/Parts
from typing import Tuple, Optional

import warnings
# Ignore all warnings
warnings.filterwarnings("ignore")

import logging
logging.basicConfig(level=logging.ERROR)

print("Libraries imported.")

# Configure ADK to use API keys directly (not Vertex AI for this multi-model setup)
os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "True"

MODEL_GEMINI_2_0_FLASH = "gemini-2.0-flash"

# --- THIS IS THE CORRECTED CELL ---

# IMPORTANT: Paste your unique API key from the Google Cloud Console here.
GOOGLE_API_KEY = "AIzaSyADEw2kuwWHrH_sOxDC4yTTadM5_uEcMjA"

# This will now work without raising an error.
print("✅ Google API Key loaded successfully.")

def get_lat_long_from_place(place: str) -> Optional[dict]:
    """
    Converts a place name into latitude and longitude using Google's Geocoding API.

    Args:
        place: A string representing a location (e.g., "Dallas, TX").

    Returns:
        A dict with keys 'latitude' and 'longitude' (floats), or None if the
        location could not be found.
    """
    GEOCODING_API_URL = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {
        'address': place,
        'key': GOOGLE_API_KEY
    }

    try:
        response = requests.get(GEOCODING_API_URL, params=params)
        response.raise_for_status()
        data = response.json()

        if data['status'] == 'OK':
            location = data['results'][0]['geometry']['location']
            latitude = location['lat']
            longitude = location['lng']
            print(f"Tool 'get_lat_long_from_place' | Input: '{place}' | Output: ({latitude}, {longitude})")
            return {"latitude": latitude, "longitude": longitude}
        else:
            print(f"Tool 'get_lat_long_from_place' | Error: {data.get('error_message', data['status'])}")
            return None
    except requests.exceptions.RequestException as e:
        print(f"Tool 'get_lat_long_from_place' | HTTP Request Error: {e}")
        return None

# --- Test the tool ---
print("Testing Geocoding Tool:")
test_result = get_lat_long_from_place("Washington, DC")
if test_result:
    test_coords = (test_result["latitude"], test_result["longitude"])
    print(f"Successfully found coordinates: {test_coords}")
else:
    test_coords = None
    print("Failed to find coordinates.")

def get_weather_from_nws(latitude: float, longitude: float) -> Optional[str]:
    """
    Retrieves the current weather forecast from the National Weather Service (NWS) API.
    """
    headers = {'User-Agent': '(Gemini Agent Demo, my-email@example.com)'}

    try:
        points_url = f"https://api.weather.gov/points/{latitude:.4f},{longitude:.4f}"
        points_response = requests.get(points_url, headers=headers)
        points_response.raise_for_status()
        forecast_url = points_response.json()['properties']['forecast']

        forecast_response = requests.get(forecast_url, headers=headers)
        forecast_response.raise_for_status()
        current_forecast = forecast_response.json()['properties']['periods'][0]

        summary = (
            f"Forecast for {current_forecast['name']}: Temp is {current_forecast['temperature']}°{current_forecast['temperatureUnit']}. "
            f"Winds from {current_forecast['windDirection']} at {current_forecast['windSpeed']}. "
            f"Expect {current_forecast['shortForecast']}. Full details: {current_forecast['detailedForecast']}"
        )
        return summary

    except Exception as e:
        print(f"Function 'get_weather_from_nws' | Error: {e}")
        return "An error occurred while fetching weather data."

# --- Test the function ---
print("\nTesting NWS Weather Function:")
if test_coords:
    weather_report = get_weather_from_nws(latitude=test_coords[0], longitude=test_coords[1])
    print(f"NWS Report: {weather_report}")
else:
    print("Skipping NWS test because coordinate test failed.")

# --- Step 4: Create the Weather Agent ---
# Using the native ADK Agent class with gemini-2.0-flash (no LiteLlm needed).
# LiteLlm is still available for multi-model scenarios, but for Gemini alone
# the native Agent is simpler and avoids a separate GEMINI_API_KEY requirement.

agent_prompt = """
You are a highly intelligent weather assistant. Your goal is to provide accurate, real-time weather forecasts from the National Weather Service.

To fulfill a user's request, you MUST follow these two steps in order:

1.  **Step 1: Get Coordinates.** First, you MUST use the `get_lat_long_from_place` tool to convert the user's requested location (e.g., "Seattle, WA") into latitude and longitude coordinates.

2.  **Step 2: Get Weather.** After you have the coordinates, you MUST use the `get_weather_from_nws` tool with the latitude and longitude you just obtained to retrieve the weather forecast.

Do not try to guess the weather. Always use the tools provided. Present the final forecast to the user in a clear and helpful manner.
"""

# Native ADK Agent — uses google-genai directly (respects GOOGLE_API_KEY / GOOGLE_GENAI_USE_VERTEXAI)
weather_agent = Agent(
    name="weather_agent",
    model=MODEL_GEMINI_2_0_FLASH,   # "gemini-2.0-flash"
    description="An agent that gets the weather forecast for a given US location.",
    instruction=agent_prompt,
    tools=[
        get_lat_long_from_place,
        get_weather_from_nws
    ]
)

print(f"✅ Agent '{weather_agent.name}' created successfully with {len(weather_agent.tools)} tools.")



import asyncio
from google.adk.runners import Runner, Event
from google.adk.sessions import InMemorySessionService
from google.genai import types
import uuid

APP_NAME   = "weather_app"
USER_ID    = "user_1"

async def run_weather_agent_tests():
    session_service = InMemorySessionService()
    runner = Runner(
        agent=weather_agent,
        app_name=APP_NAME,
        session_service=session_service
    )

    print("--- Starting Multi-Tool Weather Agent Test ---")

    test_cities = [
        "New York, NY", "Los Angeles, CA", "Chicago, IL",
        "Houston, TX", "Phoenix, AZ", "Anchorage, AK"
    ]

    for city in test_cities:
        user_query = f"What is the weather forecast for {city}?"
        session_id = str(uuid.uuid4())

        print("==========================================================")
        print(f"USER QUERY: {user_query}")
        print("----------------------------------------------------------")

        await session_service.create_session(
            app_name=APP_NAME, user_id=USER_ID, session_id=session_id
        )

        content = types.Content(role="user", parts=[types.Part(text=user_query)])
        final_response = "No text response received from agent."

        async for event in runner.run_async(
            user_id=USER_ID, session_id=session_id, new_message=content
        ):
            if isinstance(event, Event) and event.is_final_response():
                if event.content and event.content.parts and event.content.parts[0].text:
                    final_response = event.content.parts[0].text
                break

        print(f"\nFINAL AGENT RESPONSE:\n{final_response}\n")

        # <-- 2. ADD A PAUSE TO AVOID HITTING THE RATE LIMIT
        print("--- Pausing for 20 seconds to respect API rate limits... ---")
        await asyncio.sleep(20)

    print("==========================================================")
    print("--- Weather Agent Test Complete ---")

# In a notebook environment, you run the async function like this:
await run_weather_agent_tests()